apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.slurm.service: consul
  name: consul
spec:
  type: NodePort
  ports:
  - name: "8500"
    port: 8500
    targetPort: 8500
  - name: "8301"
    port: 8301
    targetPort: 8301
  selector:
    io.slurm.service: consul
status:
  loadBalancer: {}
