apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  labels:
    name: node
    role: service
  name: grafana-logging
spec:
  type: "NodePort"
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    grafana: "true"
