apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.slurm.service: slurmctld
  name: slurmctld
spec:
  ports:
  - name: "6817"
    port: 6817
    targetPort: 6817
  selector:
    io.slurm.service: slurmctld
status:
  loadBalancer: {}
