apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.slurm.service: sshd
  name: sshd
spec:
  type: NodePort
  ports:
  - name: "22"
    port: 22
    targetPort: 22
  selector:
    io.slurm.service: sshd
status:
  loadBalancer: {}
